'use client';

import {
  academicYearCreateSchema,
  academicYearUpdateSchema,
  companyCreateSchema,
  companyUpdateSchema,
  departmentCreateSchema,
  departmentUpdateSchema,
  eventCreateSchema,
  eventUpdateSchema,
  examCreateSchema,
  examUpdateSchema,
  facultyCreateSchema,
  facultyUpdateSchema,
  feeCategoryCreateSchema,
  feeCategoryUpdateSchema,
  feeCreateSchema,
  feeUpdateSchema,
  parentCreateSchema,
  parentUpdateSchema,
  placementDriveCreateSchema,
  placementDriveUpdateSchema,
  programmeCreateSchema,
  programmeUpdateSchema,
  ROLES,
  ROLE_LABELS,
  sectionCreateSchema,
  sectionUpdateSchema,
  studentCreateSchema,
  studentUpdateSchema,
  subjectCreateSchema,
  subjectUpdateSchema,
  timetableEntryCreateSchema,
  timetableEntryUpdateSchema,
  userCreateSchema,
  userUpdateSchema,
} from '@campus-connect/contracts';
import { StatusTag } from '@/components/tables/ResourceTable';
import { Figure, TwoLine } from '@/components/tables/DataTable';
import { money, shortDate } from '@/lib/utilities/format';
import type { AdminResource, AdminRow } from '../types';

const text = (key: string) => (row: AdminRow) => String(row[key] ?? '—');
const date = (key: string) => (row: AdminRow) => (row[key] ? shortDate(String(row[key])) : '—');

const Rupees = ({ value }: { value: unknown }) => <Figure>{money(Number(value ?? 0))}</Figure>;
Rupees.displayName = 'Rupees';

const StatusCell = ({ value }: { value: unknown }) => <StatusTag status={value === undefined ? undefined : String(value)} />;
StatusCell.displayName = 'StatusCell';

/** Column renderers, declared once so every table formats money and status alike. */
const rupees = (key: string) => {
  const render = (row: AdminRow) => <Rupees value={row[key]} />;
  return render;
};
const status = (row: AdminRow) => <StatusCell value={row.status} />;

const DAYS = [
  { value: '1', label: 'Monday' },
  { value: '2', label: 'Tuesday' },
  { value: '3', label: 'Wednesday' },
  { value: '4', label: 'Thursday' },
  { value: '5', label: 'Friday' },
  { value: '6', label: 'Saturday' },
  { value: '0', label: 'Sunday' },
];

/**
 * One entry per manageable entity. Columns describe the table, `fields`
 * describes the form, and the Zod pair is imported straight from the shared
 * contracts package — the exact objects the API validates with.
 */
export const ADMIN_RESOURCES: AdminResource[] = [
  {
    name: 'departments',
    title: 'Departments',
    group: 'Institution',
    singularLabel: 'department',
    description: 'Teaching departments, their block and the member of staff who heads them.',
    readPermission: 'department:read',
    writePermission: 'department:write',
    columns: [
      { key: 'code', label: 'Code', sortable: true, render: (r) => <Figure>{String(r.code)}</Figure> },
      { key: 'name', label: 'Department', sortable: true, render: (r) => <TwoLine top={String(r.name)} bottom={String(r.block || '—')} /> },
      { key: 'hodName', label: 'Head', render: (r) => text('hodUserName')(r) !== '—' ? String(r.hodUserName) : String(r.hodName || '—') },
      { key: 'studentCount', label: 'Students', align: 'right', sortable: true },
      { key: 'facultyCount', label: 'Faculty', align: 'right', sortable: true },
      { key: 'status', label: 'Status', render: status },
    ],
    fields: () => [
      { key: 'code', label: 'Department code', kind: 'text', required: true, placeholder: 'CSE' },
      { key: 'name', label: 'Department name', kind: 'text', required: true, span: 2 },
      { key: 'block', label: 'Block', kind: 'text', placeholder: 'A Block' },
      { key: 'hodName', label: 'Head of department', kind: 'text' },
    ],
    createSchema: departmentCreateSchema,
    updateSchema: departmentUpdateSchema,
  },
  {
    name: 'programmes',
    title: 'Degree programmes',
    group: 'Institution',
    singularLabel: 'programme',
    description: 'Degrees offered by each department, with their duration.',
    readPermission: 'programme:read',
    writePermission: 'programme:write',
    columns: [
      { key: 'code', label: 'Code', sortable: true, render: (r) => <Figure>{String(r.code)}</Figure> },
      { key: 'name', label: 'Programme', sortable: true, render: (r) => <TwoLine top={String(r.name)} bottom={String(r.degree)} /> },
      { key: 'department', label: 'Department' },
      { key: 'durationYears', label: 'Years', align: 'right', sortable: true },
      { key: 'status', label: 'Status', render: status },
    ],
    fields: (o) => [
      { key: 'code', label: 'Programme code', kind: 'text', required: true, placeholder: 'BE-CSE' },
      { key: 'degree', label: 'Degree', kind: 'text', required: true, placeholder: 'B.E.' },
      { key: 'name', label: 'Programme name', kind: 'text', required: true, span: 2 },
      { key: 'departmentId', label: 'Department', kind: 'select', required: true, options: o.departments },
      { key: 'durationYears', label: 'Duration (years)', kind: 'number', required: true, min: 1, max: 8 },
    ],
    createSchema: programmeCreateSchema,
    updateSchema: programmeUpdateSchema,
    filters: (o) => [{ key: 'departmentId', label: 'Department', options: o.departments }],
  },
  {
    name: 'academic-years',
    title: 'Academic years & semesters',
    group: 'Institution',
    singularLabel: 'semester',
    description: 'The academic calendar. Exactly one semester is current at a time.',
    readPermission: 'academic-year:read',
    writePermission: 'academic-year:write',
    columns: [
      { key: 'number', label: 'Semester', align: 'right', sortable: true, render: (r) => <Figure>{String(r.number)}</Figure> },
      { key: 'label', label: 'Label', sortable: true },
      { key: 'academicYear', label: 'Academic year', sortable: true },
      { key: 'isCurrent', label: 'Current', render: (r) => (r.isCurrent ? 'Yes' : '—') },
      { key: 'status', label: 'Status', render: status },
    ],
    fields: () => [
      { key: 'number', label: 'Semester number', kind: 'number', required: true, min: 1, max: 12 },
      { key: 'label', label: 'Label', kind: 'text', required: true, placeholder: 'Semester 5' },
      { key: 'academicYear', label: 'Academic year', kind: 'text', required: true, placeholder: '2026 – 27' },
      { key: 'isCurrent', label: 'Current semester', kind: 'checkbox', hint: 'Setting this clears the flag on the previous one.' },
    ],
    createSchema: academicYearCreateSchema,
    updateSchema: academicYearUpdateSchema,
  },
  {
    name: 'sections',
    title: 'Sections',
    group: 'Academics',
    singularLabel: 'section',
    description: 'Class sections and the faculty member advising each one.',
    readPermission: 'section:read',
    writePermission: 'section:write',
    columns: [
      { key: 'name', label: 'Section', sortable: true, render: (r) => <Figure>{String(r.name)}</Figure> },
      { key: 'course', label: 'Programme' },
      { key: 'semester', label: 'Semester' },
      { key: 'advisor', label: 'Class adviser', render: (r) => String(r.advisor ?? 'Unassigned') },
      { key: 'students', label: 'Students', align: 'right' },
      { key: 'status', label: 'Status', render: status },
    ],
    fields: (o) => [
      { key: 'name', label: 'Section name', kind: 'text', required: true, placeholder: 'B' },
      { key: 'courseId', label: 'Programme', kind: 'select', required: true, options: o.programmes },
      { key: 'semesterId', label: 'Semester', kind: 'select', required: true, options: o.semesters },
      { key: 'advisorFacultyId', label: 'Class adviser', kind: 'select', options: o.faculty },
    ],
    createSchema: sectionCreateSchema,
    updateSchema: sectionUpdateSchema,
    filters: (o) => [
      { key: 'semesterId', label: 'Semester', options: o.semesters },
      { key: 'courseId', label: 'Programme', options: o.programmes },
    ],
  },
  {
    name: 'subjects',
    title: 'Subjects',
    group: 'Academics',
    singularLabel: 'subject',
    description: 'Subjects per semester, and the faculty member allocated to teach each.',
    readPermission: 'subject:read',
    writePermission: 'subject:write',
    columns: [
      { key: 'code', label: 'Code', sortable: true, render: (r) => <Figure>{String(r.code)}</Figure> },
      { key: 'name', label: 'Subject', sortable: true, render: (r) => <TwoLine top={String(r.name)} bottom={String(r.shortName)} /> },
      { key: 'kind', label: 'Kind' },
      { key: 'credits', label: 'Credits', align: 'right', sortable: true },
      { key: 'faculty', label: 'Faculty' },
      { key: 'semester', label: 'Semester' },
      { key: 'status', label: 'Status', render: status },
    ],
    fields: (o) => [
      { key: 'code', label: 'Subject code', kind: 'text', required: true, placeholder: 'CS501' },
      { key: 'shortName', label: 'Short name', kind: 'text', required: true, placeholder: 'Networks' },
      { key: 'name', label: 'Subject name', kind: 'text', required: true, span: 2 },
      { key: 'kind', label: 'Kind', kind: 'select', required: true, options: [{ value: 'THEORY', label: 'Theory' }, { value: 'PRACTICAL', label: 'Practical' }] },
      { key: 'credits', label: 'Credits', kind: 'number', required: true, min: 0, max: 12 },
      { key: 'room', label: 'Default room', kind: 'text' },
      { key: 'departmentId', label: 'Department', kind: 'select', required: true, options: o.departments },
      { key: 'semesterId', label: 'Semester', kind: 'select', required: true, options: o.semesters },
      { key: 'facultyId', label: 'Faculty', kind: 'select', options: o.faculty },
    ],
    createSchema: subjectCreateSchema,
    updateSchema: subjectUpdateSchema,
    filters: (o) => [
      { key: 'departmentId', label: 'Department', options: o.departments },
      { key: 'semesterId', label: 'Semester', options: o.semesters },
      { key: 'facultyId', label: 'Faculty', options: o.faculty },
    ],
  },
  {
    name: 'students',
    title: 'Students',
    group: 'People',
    singularLabel: 'student',
    description: 'The student roll. Creating one also opens their portal account.',
    readPermission: 'student:read',
    writePermission: 'student:write',
    columns: [
      { key: 'registerNumber', label: 'Register no.', sortable: true, render: (r) => <Figure>{String(r.registerNumber)}</Figure> },
      { key: 'name', label: 'Student', render: (r) => <TwoLine top={String(r.name)} bottom={String(r.email)} /> },
      { key: 'department', label: 'Dept.' },
      { key: 'section', label: 'Section' },
      { key: 'batch', label: 'Batch', sortable: true },
      { key: 'mobile', label: 'Mobile' },
      { key: 'status', label: 'Status', render: status },
    ],
    fields: (o) => [
      { key: 'name', label: 'Full name', kind: 'text', required: true, span: 2 },
      { key: 'email', label: 'Institute email', kind: 'email', required: true, span: 2 },
      { key: 'registerNumber', label: 'Register number', kind: 'text', required: true },
      { key: 'batch', label: 'Batch', kind: 'text', required: true, placeholder: '2022 – 26' },
      { key: 'dateOfBirth', label: 'Date of birth', kind: 'date', required: true },
      { key: 'bloodGroup', label: 'Blood group', kind: 'text', placeholder: 'O+' },
      { key: 'mobile', label: 'Mobile', kind: 'phone', required: true },
      { key: 'residence', label: 'Residence', kind: 'text', placeholder: 'Hosteller' },
      { key: 'admissionQuota', label: 'Admission quota', kind: 'text' },
      { key: 'mentorName', label: 'Mentor', kind: 'text' },
      { key: 'departmentId', label: 'Department', kind: 'select', required: true, options: o.departments },
      { key: 'courseId', label: 'Programme', kind: 'select', required: true, options: o.programmes },
      { key: 'sectionId', label: 'Section', kind: 'select', required: true, options: o.sections },
      { key: 'photoFileId', label: 'Photograph', kind: 'image', purpose: 'STUDENT_PHOTO', hint: 'Stored in object storage; only the URL is kept.' },
    ],
    createSchema: studentCreateSchema,
    updateSchema: studentUpdateSchema,
    filters: (o) => [
      { key: 'departmentId', label: 'Department', options: o.departments },
      { key: 'sectionId', label: 'Section', options: o.sections },
    ],
  },
  {
    name: 'faculty',
    title: 'Faculty',
    group: 'People',
    singularLabel: 'faculty member',
    description: 'Teaching staff. Marking someone as head gives their account the HOD role.',
    readPermission: 'faculty:read',
    writePermission: 'faculty:write',
    columns: [
      { key: 'staffId', label: 'Staff ID', sortable: true, render: (r) => <Figure>{String(r.staffId)}</Figure> },
      { key: 'name', label: 'Name', render: (r) => <TwoLine top={String(r.name)} bottom={String(r.email)} /> },
      { key: 'designation', label: 'Designation', sortable: true },
      { key: 'department', label: 'Dept.' },
      { key: 'hours', label: 'Weekly hours', align: 'right' },
      { key: 'isHead', label: 'Head', render: (r) => (r.isHead ? 'Yes' : '—') },
      { key: 'status', label: 'Status', render: status },
    ],
    fields: (o) => [
      { key: 'name', label: 'Full name', kind: 'text', required: true, span: 2 },
      { key: 'email', label: 'Institute email', kind: 'email', required: true, span: 2 },
      { key: 'staffId', label: 'Staff ID', kind: 'text', required: true },
      { key: 'designation', label: 'Designation', kind: 'text', required: true },
      { key: 'qualification', label: 'Qualification', kind: 'text' },
      { key: 'experienceYears', label: 'Experience (years)', kind: 'number', required: true, min: 0, max: 60 },
      { key: 'cabin', label: 'Cabin', kind: 'text' },
      { key: 'mobile', label: 'Mobile', kind: 'phone', required: true },
      { key: 'joinedOn', label: 'Date of joining', kind: 'date', required: true },
      { key: 'departmentId', label: 'Department', kind: 'select', required: true, options: o.departments },
      { key: 'isHead', label: 'Head of department', kind: 'checkbox' },
    ],
    createSchema: facultyCreateSchema,
    updateSchema: facultyUpdateSchema,
    filters: (o) => [{ key: 'departmentId', label: 'Department', options: o.departments }],
  },
  {
    name: 'parents',
    title: 'Parent accounts',
    group: 'People',
    singularLabel: 'parent account',
    description: 'Guardian logins, each linked to exactly one ward.',
    readPermission: 'parent:read',
    writePermission: 'parent:write',
    columns: [
      { key: 'name', label: 'Guardian', render: (r) => <TwoLine top={String(r.name)} bottom={String(r.email)} /> },
      { key: 'relation', label: 'Relation', sortable: true },
      { key: 'mobile', label: 'Mobile' },
      { key: 'ward', label: 'Ward', render: (r) => <TwoLine top={String(r.ward)} bottom={String(r.wardRegisterNumber)} /> },
      { key: 'status', label: 'Status', render: status },
    ],
    fields: (o) => [
      { key: 'name', label: 'Full name', kind: 'text', required: true, span: 2 },
      { key: 'email', label: 'Email', kind: 'email', required: true, span: 2 },
      { key: 'relation', label: 'Relation', kind: 'text', required: true, placeholder: 'Father' },
      { key: 'mobile', label: 'Mobile', kind: 'phone', required: true },
      { key: 'wardId', label: 'Ward', kind: 'select', required: true, options: o.students, span: 2 },
    ],
    createSchema: parentCreateSchema,
    updateSchema: parentUpdateSchema,
  },
  {
    name: 'users',
    title: 'Accounts & roles',
    group: 'People',
    singularLabel: 'account',
    description: 'Portal logins and the role each one carries. New accounts start on the shared initial password.',
    readPermission: 'user:read',
    writePermission: 'user:write',
    columns: [
      { key: 'loginId', label: 'Login ID', sortable: true, render: (r) => <Figure>{String(r.loginId)}</Figure> },
      { key: 'name', label: 'Name', sortable: true, render: (r) => <TwoLine top={String(r.name)} bottom={String(r.email)} /> },
      { key: 'roleLabel', label: 'Role', sortable: true },
      { key: 'department', label: 'Department' },
      { key: 'status', label: 'Status', render: status },
    ],
    fields: (o) => [
      { key: 'name', label: 'Full name', kind: 'text', required: true, span: 2 },
      { key: 'email', label: 'Email', kind: 'email', required: true, span: 2 },
      { key: 'role', label: 'Role', kind: 'select', required: true, options: ROLES.map((r) => ({ value: r, label: ROLE_LABELS[r] })) },
      { key: 'departmentCode', label: 'Department code', kind: 'select', options: o.departments.map((d) => ({ value: d.label.split(' · ')[0], label: d.label })) },
      { key: 'extra', label: 'Subtitle', kind: 'text', hint: 'Shown under the name in the header.', span: 2 },
    ],
    createSchema: userCreateSchema,
    updateSchema: userUpdateSchema,
  },
  {
    name: 'timetable',
    title: 'Timetable',
    group: 'Academics',
    singularLabel: 'timetable entry',
    description: 'Period-by-period allocation of subjects, faculty and rooms to sections.',
    readPermission: 'timetable:read',
    writePermission: 'timetable:write',
    columns: [
      { key: 'day', label: 'Day', sortable: true },
      { key: 'period', label: 'Period', align: 'right', sortable: true },
      { key: 'startTime', label: 'From', render: (r) => `${r.startTime} – ${r.endTime}` },
      { key: 'section', label: 'Section' },
      { key: 'subject', label: 'Subject' },
      { key: 'faculty', label: 'Faculty' },
      { key: 'room', label: 'Room' },
    ],
    fields: (o) => [
      { key: 'dayOfWeek', label: 'Day', kind: 'select', required: true, options: DAYS },
      { key: 'period', label: 'Period', kind: 'number', required: true, min: 1, max: 10 },
      { key: 'startTime', label: 'From', kind: 'time', required: true },
      { key: 'endTime', label: 'To', kind: 'time', required: true },
      { key: 'sectionId', label: 'Section', kind: 'select', required: true, options: o.sections },
      { key: 'semesterId', label: 'Semester', kind: 'select', required: true, options: o.semesters },
      { key: 'subjectId', label: 'Subject', kind: 'select', options: o.subjects },
      { key: 'facultyId', label: 'Faculty', kind: 'select', options: o.faculty },
      { key: 'room', label: 'Room', kind: 'text' },
      { key: 'label', label: 'Label', kind: 'text', hint: 'For a free period — Library, Sports.' },
    ],
    createSchema: timetableEntryCreateSchema,
    updateSchema: timetableEntryUpdateSchema,
    filters: (o) => [
      { key: 'sectionId', label: 'Section', options: o.sections },
      { key: 'facultyId', label: 'Faculty', options: o.faculty },
      { key: 'dayOfWeek', label: 'Day', options: DAYS },
    ],
  },
  {
    name: 'fee-categories',
    title: 'Fee categories',
    group: 'Finance',
    singularLabel: 'fee category',
    description: 'Heads of fee defined once, then assigned to students.',
    readPermission: 'fee:read',
    writePermission: 'fee:write',
    columns: [
      { key: 'code', label: 'Code', sortable: true, render: (r) => <Figure>{String(r.code)}</Figure> },
      { key: 'name', label: 'Category', sortable: true },
      { key: 'defaultAmount', label: 'Default amount', align: 'right', sortable: true, render: rupees('defaultAmount') },
      { key: 'academicYear', label: 'Academic year' },
      { key: 'assignments', label: 'Assigned', align: 'right' },
      { key: 'status', label: 'Status', render: status },
    ],
    fields: () => [
      { key: 'code', label: 'Category code', kind: 'text', required: true, placeholder: 'TUITION' },
      { key: 'name', label: 'Category name', kind: 'text', required: true },
      { key: 'defaultAmount', label: 'Default amount (₹)', kind: 'number', required: true, min: 0 },
      { key: 'academicYear', label: 'Academic year', kind: 'text', required: true, placeholder: '2026 – 27' },
      { key: 'description', label: 'Description', kind: 'textarea', span: 2 },
    ],
    createSchema: feeCategoryCreateSchema,
    updateSchema: feeCategoryUpdateSchema,
  },
  {
    name: 'fees',
    title: 'Student fee assignments',
    group: 'Finance',
    singularLabel: 'fee assignment',
    description: 'Heads of fee raised against a student. A settled head is frozen — record a reversal rather than editing it.',
    readPermission: 'fee:read',
    writePermission: 'fee:write',
    archivable: false,
    columns: [
      { key: 'registerNumber', label: 'Register no.', render: (r) => <Figure>{String(r.registerNumber)}</Figure> },
      { key: 'student', label: 'Student' },
      { key: 'head', label: 'Head of fee', sortable: true },
      { key: 'amount', label: 'Amount', align: 'right', sortable: true, render: rupees('amount') },
      { key: 'dueDate', label: 'Due', sortable: true, render: date('dueDate') },
      { key: 'settlement', label: 'Settlement', render: (r) => <StatusTag status={r.settlement === 'PAID' ? 'ACTIVE' : 'ARCHIVED'} /> },
      { key: 'receipt', label: 'Receipt', render: (r) => String(r.receipt ?? '—') },
    ],
    fields: (o) => [
      { key: 'studentId', label: 'Student', kind: 'select', required: true, options: o.students, span: 2 },
      { key: 'categoryId', label: 'Category', kind: 'select', options: o.feeCategories },
      { key: 'head', label: 'Head of fee', kind: 'text', required: true },
      { key: 'amount', label: 'Amount (₹)', kind: 'number', required: true, min: 0 },
      { key: 'dueDate', label: 'Due date', kind: 'date', required: true },
      { key: 'academicYear', label: 'Academic year', kind: 'text', required: true, placeholder: '2026 – 27' },
    ],
    createSchema: feeCreateSchema,
    updateSchema: feeUpdateSchema,
    filters: (o) => [
      { key: 'categoryId', label: 'Category', options: o.feeCategories },
      { key: 'paymentStatus', label: 'Settlement', options: [{ value: 'PENDING', label: 'Pending' }, { value: 'PAID', label: 'Paid' }] },
    ],
  },
  {
    name: 'examinations',
    title: 'Examinations',
    group: 'Academics',
    singularLabel: 'examination',
    description: 'The examination timetable, hall allotment and candidate strength.',
    readPermission: 'examination:read',
    writePermission: 'examination:write',
    columns: [
      { key: 'date', label: 'Date', sortable: true, render: date('date') },
      { key: 'session', label: 'Session' },
      { key: 'code', label: 'Code', render: (r) => <Figure>{String(r.code)}</Figure> },
      { key: 'subject', label: 'Subject', render: (r) => <TwoLine top={String(r.subject)} bottom={String(r.title)} /> },
      { key: 'hall', label: 'Hall' },
      { key: 'strength', label: 'Strength', align: 'right' },
      { key: 'status', label: 'Status', render: status },
    ],
    fields: (o) => [
      { key: 'title', label: 'Examination title', kind: 'text', required: true, span: 2, placeholder: 'End Semester Examination' },
      { key: 'subjectId', label: 'Subject', kind: 'select', required: true, options: o.subjects, span: 2 },
      { key: 'date', label: 'Date', kind: 'date', required: true },
      { key: 'session', label: 'Session', kind: 'select', required: true, options: [{ value: 'Forenoon', label: 'Forenoon' }, { value: 'Afternoon', label: 'Afternoon' }] },
      { key: 'hall', label: 'Hall', kind: 'text' },
      { key: 'seatNo', label: 'Seat number', kind: 'text' },
      { key: 'strength', label: 'Candidate strength', kind: 'number', min: 0 },
    ],
    createSchema: examCreateSchema,
    updateSchema: examUpdateSchema,
    filters: (o) => [{ key: 'subjectId', label: 'Subject', options: o.subjects }],
  },
  {
    name: 'events',
    title: 'Events & holidays',
    group: 'Engagement',
    singularLabel: 'event',
    description: 'Everything that appears on the academic calendar.',
    readPermission: 'calendar:read',
    writePermission: 'calendar:write',
    columns: [
      { key: 'date', label: 'Date', sortable: true, render: date('date') },
      { key: 'title', label: 'Event', sortable: true },
      { key: 'tag', label: 'Tag', sortable: true },
      { key: 'status', label: 'Status', render: status },
    ],
    fields: () => [
      { key: 'title', label: 'Event title', kind: 'text', required: true, span: 2 },
      { key: 'date', label: 'Date', kind: 'date', required: true },
      { key: 'tag', label: 'Tag', kind: 'text', required: true, placeholder: 'Holiday' },
      {
        key: 'tone',
        label: 'Emphasis',
        kind: 'select',
        options: [
          { value: 'ACCENT', label: 'Standard' },
          { value: 'OK', label: 'Positive' },
          { value: 'WARN', label: 'Attention' },
          { value: 'BAD', label: 'Critical' },
        ],
      },
    ],
    createSchema: eventCreateSchema,
    updateSchema: eventUpdateSchema,
  },
  {
    name: 'companies',
    title: 'Placement companies',
    group: 'Engagement',
    singularLabel: 'company',
    description: 'Recruiters, entered once and referenced by every drive.',
    readPermission: 'placement:read',
    writePermission: 'placement:write',
    columns: [
      { key: 'name', label: 'Company', sortable: true },
      { key: 'sector', label: 'Sector', sortable: true },
      { key: 'contactName', label: 'Contact', render: (r) => <TwoLine top={String(r.contactName || '—')} bottom={String(r.contactEmail || '—')} /> },
      { key: 'drives', label: 'Drives', align: 'right' },
      { key: 'status', label: 'Status', render: status },
    ],
    fields: () => [
      { key: 'name', label: 'Company name', kind: 'text', required: true, span: 2 },
      { key: 'sector', label: 'Sector', kind: 'text' },
      { key: 'website', label: 'Website', kind: 'text' },
      { key: 'contactName', label: 'Contact name', kind: 'text' },
      { key: 'contactEmail', label: 'Contact email', kind: 'email' },
      { key: 'contactPhone', label: 'Contact phone', kind: 'phone' },
    ],
    createSchema: companyCreateSchema,
    updateSchema: companyUpdateSchema,
  },
  {
    name: 'placement-drives',
    title: 'Placement drives',
    group: 'Engagement',
    singularLabel: 'placement drive',
    description: 'Campus drives with their eligibility bar and registration count.',
    readPermission: 'placement:read',
    writePermission: 'placement:write',
    columns: [
      { key: 'driveDate', label: 'Date', sortable: true, render: date('driveDate') },
      { key: 'company', label: 'Company', sortable: true },
      { key: 'role', label: 'Role', render: (r) => <TwoLine top={String(r.role)} bottom={String(r.ctc)} /> },
      { key: 'minCgpa', label: 'Min CGPA', align: 'right', sortable: true },
      { key: 'registrations', label: 'Registered', align: 'right' },
      { key: 'status', label: 'Status', render: status },
    ],
    fields: (o) => [
      { key: 'company', label: 'Company name', kind: 'text', required: true, span: 2 },
      { key: 'companyId', label: 'Linked company record', kind: 'select', options: o.companies, span: 2 },
      { key: 'role', label: 'Role', kind: 'text', required: true },
      { key: 'ctc', label: 'CTC', kind: 'text', required: true, placeholder: '₹9.5 LPA' },
      { key: 'driveDate', label: 'Drive date', kind: 'date', required: true },
      { key: 'minCgpa', label: 'Minimum CGPA', kind: 'number', required: true, min: 0, max: 10 },
      { key: 'noArrears', label: 'No arrears required', kind: 'checkbox' },
      { key: 'eligibility', label: 'Eligibility note', kind: 'textarea', span: 2 },
    ],
    createSchema: placementDriveCreateSchema,
    updateSchema: placementDriveUpdateSchema,
    filters: (o) => [{ key: 'companyId', label: 'Company', options: o.companies }],
  },
];

export const RESOURCE_GROUPS = [...new Set(ADMIN_RESOURCES.map((r) => r.group))];
